-- Migration 000: Core operational tables
-- These 9 tables (products, sales, expenses, debts, replenishments,
-- ingredients, app_config, active_sessions, activity_logs) were originally
-- created by hand in the Supabase Table Editor when this project was first
-- built, never through a migration file -- so 001_auth_and_rls.sql onward
-- (which ALTERs RLS and adds policies on all of them) always assumed they
-- already existed. Reconstructed here from production's live schema via
-- information_schema/pg_catalog introspection so a fresh project can be
-- bootstrapped from supabase/migrations/ alone. Numbered 000 so it runs
-- before 001, which depends on these tables existing.

CREATE TABLE IF NOT EXISTS public.products (
    id text PRIMARY KEY,
    name text NOT NULL,
    stock integer NOT NULL,
    min integer NOT NULL,
    max integer NOT NULL,
    unit text DEFAULT 'unid.'::text,
    price numeric NOT NULL,
    category text DEFAULT 'pastelitos'::text,
    updated_at timestamp with time zone DEFAULT now(),
    initial_stock integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.sales (
    uuid text PRIMARY KEY,
    product_id text NOT NULL,
    name text NOT NULL,
    price numeric NOT NULL,
    timestamp timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.expenses (
    uuid text PRIMARY KEY,
    description text NOT NULL,
    amount numeric NOT NULL,
    timestamp timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.debts (
    uuid text PRIMARY KEY,
    client_name text NOT NULL,
    amount numeric NOT NULL,
    description text,
    timestamp timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.replenishments (
    uuid text PRIMARY KEY,
    product_id text NOT NULL,
    name text NOT NULL,
    amount integer NOT NULL,
    unit text DEFAULT 'unid.'::text,
    status text DEFAULT 'en_camino'::text,
    timestamp timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ingredients (
    id text PRIMARY KEY,
    name text NOT NULL,
    stock numeric NOT NULL,
    unit text DEFAULT 'kg'::text,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.app_config (
    id integer PRIMARY KEY DEFAULT 1,
    bcv_rate numeric NOT NULL DEFAULT 732.48,
    use_auto_bcv boolean NOT NULL DEFAULT true,
    updated_at timestamp with time zone DEFAULT now(),
    totp_secret text,
    totp_enabled boolean DEFAULT false,
    last_close_time timestamp with time zone,
    CONSTRAINT app_config_id_check CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS public.active_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id text NOT NULL UNIQUE,
    device_name text NOT NULL,
    role text NOT NULL,
    last_active_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    is_blocked boolean NOT NULL DEFAULT false,
    is_trusted boolean NOT NULL DEFAULT false
);

-- id has no client-supplied value on insert anywhere in the app (see
-- insertActivityLog in js/supabase.js), so it must self-generate.
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role text NOT NULL,
    action text NOT NULL,
    details text,
    timestamp timestamp with time zone DEFAULT now()
);

-- Single-row config table; app_config.id is always 1 (see fetchAppConfig in
-- js/supabase.js, which queries .eq('id', 1)).
INSERT INTO public.app_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
